### ISSUE TITLE
module lack

### ISSUE THREAD

**Issue by flag7** [melkael/mcts_vne#1]
sorry for bothering you, i am just getting into the learning of vne and vne-with-rl.
The documents i downloaded of agent.py seems to lack the module of virtual node mapping 
i would be very appreciate if it is ok for you to provide the "VNoM" to me, it will be a great assistant for me to learn the vne

**Comment by melkael** [comment]
Hello, no problem.

This is a relatively old repo. I rewrote most of it as well as other algorithms. I can make my updated repo available soon if you would be interested. All algorithms are written in Julia, which has a syntax close to python but the code is 100ish times faster

**Comment by flag7** [comment]
I am not sure if you received my reply email after your answer because I can not check it on github, so I paste it below.

Thank you very much for your answer .

It will be a great help for my study.Actually I am not majored in programming,so I wonder if it is necessary to download specific platform to run the Julia code ,or it is ok for other app(maybe stupid ).I learned a little about c language but not enough to use vne-sim to simulate,so I run the code on pycharm and sometimes matlab.
Thank you again for your repository and response.

**Comment by melkael** [comment]
Hello,

I just published the Julia implementation. You will also find code for other papers, including NEPA which is currently in review, the arxiv preprint should be online very soon.

Please find the repo here: https://github.com/melkael/vne

**Comment by flag7** [comment]
Hello,

I am so appreciated for your uploaded code. It will be a great help to my study in vne. I will note the method in my paper later. Good luck with your academic.

**Comment by melkael** [comment]
Thank you, please find the preprint explaining the NEPA algorithm here:
https://arxiv.org/abs/2202.13706

Sorry for the late reply and good luck to you too !
